=

== Build the project
Building the project will create 2 applications (jars)

* web.jar
* repositories-mem.jar

----
mvn clean package
----

== Running the applications
Run in 2 consoles:

----
java -jar web/target/web.jar --remoteHost=localhost --remotePort=9091 --server.port=8091
----

and

----
java -jar repositories-mem/target/repositories-mem.jar --server.port=9091
----

== Test the applications
You can test the applications either by going into the console at, which will use application *web* or use direcly the Rest interface on application *repository-mem*.

Some examples:

Web interface:

----
http://localhost:8091
----

Rest commands:

----
ADD ONE: curl  -H "Content-type: application/json" -X POST -d '{"id":10,"text":"AAAA","summary":"BBBB"}'  http://localhost:9091/
MODIFY ONE : curl  -H "Content-type: application/json" -X PUT -d '{"id":10,"text":"aaaaa","summary":"bbbbb"}'  http://localhost:9091/10
GET ALL: curl http://localhost:9091/
GET ONE: curl http://localhost:9091/1
DELETE ONE: curl -X DELETE http://localhost:9091/10
----

== Run at openshift
see also https://blog.openshift.com/using-openshift-enterprise-grade-spring-boot-deployments/

=== Prequisite
Create springboot-sti project as instructed in this same github repository (see https://github.com/tecong/springboot-on-openshift-examples/tree/master/spring-boot/springboot-sti)

=== Info
Following steps creates application build and deployment pipeline dev,test,prod. Build is embedded at openshift side and it utilizes source to image technology (s2i). Application consists of two containers, one running UI and other running backend repository service with embedded database (HSQL). Application is built with spring boot framework and maven.

=== Steps to create openshift pipeline
Create applications and simulate running at dev and test versions from different tags

Create project and allow access to project where springboot builder image resides:

----
oc new-project microservices-demo-springboot
oc policy add-role-to-group \
system:image-puller system:serviceaccounts:microservices-demo-springboot \
--namespace=springboot-sti
oc policy add-role-to-user admin "CN=Pasi Kilponen,OU=Users,OU=IBM Cloud,DC=tieto,DC=softlayer,DC=local" -n microservices-demo-springboot
----

Create repository container, APP_OPTIONS is passed to java run command. 

----
oc new-app springboot-sti/springboot-sti~https://github.com/tecong/springboot-on-openshift-examples.git \
--context-dir=spring-boot/sample-microservices-springboot/repositories-mem \
--name=repository-mem \
-e APP_OPTIONS="--server.port=8080"

oc new-app springboot-sti/springboot-sti~https://github.com/tecong/springboot-on-openshift-examples.git \
--context-dir=spring-boot/sample-microservices-springboot/web --name=web \
-e APP_OPTIONS="--remoteHost=repository-mem --remotePort=8080 --server.port=8080"
----

Test endpoints

----
oc get svc <<< see clusterip
curl -L -v http://172.30.70.130:8080 <<< (:9090 repository-mem)
----

At this point group application components together in OpenShift console by selecting first web pod and then clicking group service at selected pod. That will show hole application as one group in console making it more easy to see how the pipeline is build; you will then have group per deployment e.g. dev, test, prod.

Next step is to tag images at repository with test tag and create associated application delpoyments for test. Note the difference at oc new-app command which in this time directly asks to deploy from given image and tag (e.g. web:test).

----
oc tag repository-mem:latest repository-mem:test
oc tag web:latest web:test

oc new-app repository-mem:test \
--name=repository-mem-test \
-e APP_OPTIONS="--server.port=8080"

oc new-app web:test \
--name=web-test \
-e APP_OPTIONS="--remoteHost=repository-mem-test --remotePort=8080 --server.port=8080"
----

Add prod application pipeline is similar to test environment creation:

Promote application to production

----
oc tag repository-mem:test repository-mem:prod
oc tag web:test web:prod

oc new-app repository-mem:prod \
--name=repository-mem-prod \
-e APP_OPTIONS="--server.port=8080"

oc new-app web:prod \
--name=web-test \
-e APP_OPTIONS="--remoteHost=repository-mem-prod --remotePort=8080 --server.port=8080"
----

